// ---------------------------------------------------------------------------
// audio.js — every sound here is generated by the browser. No files.
//
// Two kinds of sound live here:
//
//   CONTINUOUS  the motor, servo, wheels and hum. These never stop. They run
//               forever and we only slide their volumes, because starting and
//               stopping oscillators makes a click.
//
//   ONE-SHOTS   the launcher firing, a treat landing. These are built fresh
//               each time, given a quick volume envelope, and thrown away.
// ---------------------------------------------------------------------------

import { CONFIG } from './config.js';

export function createAudio() {
  let ctx = null;
  let master, motorOsc, motorGain, motorFilter;
  let whineOsc, whineGain, rumbleGain, rumbleFilter, rumbleFilter2;
  let servoOsc, servoGain, servoFilter;
  let noiseBuffer;
  let muted = false;

  /**
   * Two seconds of brown noise. Integrating white noise pushes energy into the
   * low end, which is what makes a rumble instead of a hiss. The smaller the
   * coefficient, the deeper and softer the result — 0.008 is well below the
   * usual 0.02, because anything brighter reads as scratching.
   *
   * Normalising at the end means the coefficient can be changed freely
   * without the volume jumping around.
   */
  function makeNoise() {
    const buf = ctx.createBuffer(1, ctx.sampleRate * 2, ctx.sampleRate);
    const data = buf.getChannelData(0);
    let last = 0;
    let peak = 0;
    for (let i = 0; i < data.length; i++) {
      const white = Math.random() * 2 - 1;
      last = (last + 0.008 * white) / 1.008;
      data[i] = last;
      if (Math.abs(last) > peak) peak = Math.abs(last);
    }
    if (peak > 0) for (let i = 0; i < data.length; i++) data[i] /= peak;
    return buf;
  }

  /** Build the whole graph. Called once, on the first click or keypress. */
  function build() {
    const AC = window.AudioContext || window.webkitAudioContext;
    if (!AC) return;
    ctx = new AC();

    master = ctx.createGain();
    master.gain.value = 0.9;
    master.connect(ctx.destination);

    noiseBuffer = makeNoise();

    // --- drive motor -------------------------------------------------------
    motorOsc = ctx.createOscillator();
    motorOsc.type = 'sawtooth';
    motorOsc.frequency.value = 40;

    motorFilter = ctx.createBiquadFilter();
    motorFilter.type = 'lowpass';
    motorFilter.frequency.value = 300;
    motorFilter.Q.value = 2;

    motorGain = ctx.createGain();
    motorGain.gain.value = 0;

    motorOsc.connect(motorFilter).connect(motorGain).connect(master);
    motorOsc.start();

    // --- servo whine --------------------------------------------------------
    // Triangle, not square. A square wave is all odd harmonics and it is
    // genuinely painful at this frequency; a triangle rolls off fast and
    // sits under the motor instead of on top of your ear.
    whineOsc = ctx.createOscillator();
    whineOsc.type = 'triangle';
    whineOsc.frequency.value = 300;

    whineGain = ctx.createGain();
    whineGain.gain.value = 0;

    whineOsc.connect(whineGain).connect(master);
    whineOsc.start();

    // --- pan/tilt servo -----------------------------------------------------
    // A stepper motor whirr. A sawtooth squeezed through a narrow bandpass
    // gives you the buzzy, harmonic-rich quality of a small geared motor —
    // much closer than any pure tone.
    servoOsc = ctx.createOscillator();
    servoOsc.type = 'sawtooth';
    servoOsc.frequency.value = 200;

    servoFilter = ctx.createBiquadFilter();
    servoFilter.type = 'bandpass';
    servoFilter.frequency.value = 850;
    servoFilter.Q.value = 3.5;

    servoGain = ctx.createGain();
    servoGain.gain.value = 0;

    servoOsc.connect(servoFilter).connect(servoGain).connect(master);
    servoOsc.start();

    // --- wheels on the surface ---------------------------------------------
    const rumbleSrc = ctx.createBufferSource();
    rumbleSrc.buffer = noiseBuffer;
    rumbleSrc.loop = true;

    // TWO lowpass filters in series, not one. A single biquad rolls off at
    // 12dB per octave, which lets plenty of high end through — and high end
    // on noise is exactly what "scratching" sounds like. Chaining two doubles
    // that to 24dB and the harshness goes away.
    //
    // Q below 1 keeps them from resonating at the cutoff, which would add a
    // whistle right where we are trying to remove one.
    rumbleFilter = ctx.createBiquadFilter();
    rumbleFilter.type = 'lowpass';
    rumbleFilter.frequency.value = 620;
    rumbleFilter.Q.value = 0.6;

    rumbleFilter2 = ctx.createBiquadFilter();
    rumbleFilter2.type = 'lowpass';
    rumbleFilter2.frequency.value = 620;
    rumbleFilter2.Q.value = 0.6;

    rumbleGain = ctx.createGain();
    rumbleGain.gain.value = 0;

    rumbleSrc.connect(rumbleFilter).connect(rumbleFilter2).connect(rumbleGain).connect(master);
    rumbleSrc.start();

    // --- the device being on ------------------------------------------------
    const hum = ctx.createOscillator();
    hum.type = 'sine';
    hum.frequency.value = 58;
    const humGain = ctx.createGain();
    humGain.gain.value = 0.005;
    hum.connect(humGain).connect(master);
    hum.start();
  }

  // --- one-shot helpers -----------------------------------------------------

  /** A short tone that slides in pitch and fades out. */
  function tone(type, from, to, dur, vol) {
    const o = ctx.createOscillator();
    const g = ctx.createGain();
    o.type = type;
    o.frequency.setValueAtTime(from, ctx.currentTime);
    o.frequency.exponentialRampToValueAtTime(Math.max(1, to), ctx.currentTime + dur);
    g.gain.setValueAtTime(vol, ctx.currentTime);
    g.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + dur);
    o.connect(g).connect(master);
    o.start();
    o.stop(ctx.currentTime + dur + 0.02);
  }

  /** A burst of noise through a band-pass — clatter, rattle, scuff. */
  function burst(freq, q, dur, vol) {
    const s = ctx.createBufferSource();
    s.buffer = noiseBuffer;
    s.loop = true;

    const f = ctx.createBiquadFilter();
    f.type = 'bandpass';
    f.frequency.value = freq;
    f.Q.value = q;

    const g = ctx.createGain();
    g.gain.setValueAtTime(vol, ctx.currentTime);
    g.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + dur);

    s.connect(f).connect(g).connect(master);
    s.start();
    s.stop(ctx.currentTime + dur + 0.02);
  }

  return {
    start() {
      if (!ctx) build();
      if (ctx && ctx.state === 'suspended') ctx.resume();
    },

    /**
     * Called every frame. Nothing switches on or off — we only slide volumes
     * and filter cutoffs towards where they should be.
     *
     * setTargetAtTime glides to a value instead of jumping to it. Jumping
     * causes clicks. This is the whole reason it exists.
     */
    update(vel, angVel, surface, aim = 0) {
      if (!ctx || muted) return;
      const t = ctx.currentTime;

      const drive = Math.min(1, Math.abs(vel) / CONFIG.robot.moveSpeed);
      const turn = Math.min(1, Math.abs(angVel) / CONFIG.robot.turnSpeed);
      const effort = Math.max(drive, turn);

      motorGain.gain.setTargetAtTime(effort * 0.016, t, 0.06);
      motorOsc.frequency.setTargetAtTime(38 + drive * 20 + turn * 22, t, 0.07);
      motorFilter.frequency.setTargetAtTime(240 + effort * 260, t, 0.09);

      whineGain.gain.setTargetAtTime(turn * 0.0028, t, 0.05);
      whineOsc.frequency.setTargetAtTime(280 + turn * 130, t, 0.06);

      // The rug swallows what is left of the high end and most of the volume.
      // Both cutoffs stay low: the point is to FEEL the surface change, not to
      // hear the floor being sanded. A slow time constant means you roll onto
      // the rug rather than the sound switching over.
      const onRug = surface === 'rug';
      const cutoff = onRug ? 290 : 620;
      rumbleGain.gain.setTargetAtTime(drive * (onRug ? 0.035 : 0.075), t, 0.12);
      rumbleFilter.frequency.setTargetAtTime(cutoff, t, 0.18);
      rumbleFilter2.frequency.setTargetAtTime(cutoff, t, 0.18);

      // The camera head panning and tilting. Its own voice, separate from the
      // drive motor, because they are separate motors on a real unit.
      const pan = Math.min(1, aim);
      servoGain.gain.setTargetAtTime(pan * 0.013, t, 0.04);
      servoOsc.frequency.setTargetAtTime(185 + pan * 95, t, 0.05);
      servoFilter.frequency.setTargetAtTime(760 + pan * 430, t, 0.06);
    },

    /** The launcher. A servo kick, then the treat rattling out of the chute. */
    fire(charge = 0.5) {
      if (!ctx || muted) return;
      tone('square', 180 + charge * 90, 60, 0.07, 0.05);
      burst(2200, 1.4, 0.09, 0.09);
    },

    /** A treat hitting something. */
    land() {
      if (!ctx || muted) return;
      burst(3400, 3, 0.045, 0.045);
    },

    /** Pressing TREAT with an empty hopper: the motor turns over, nothing comes. */
    empty() {
      if (!ctx || muted) return;
      tone('square', 120, 70, 0.05, 0.025);
    },

    toggleMute() {
      muted = !muted;
      if (ctx) master.gain.setTargetAtTime(muted ? 0 : 0.9, ctx.currentTime, 0.02);
      return muted;
    },
  };
}
